--- Insert de Área
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 1, 1, 'SERVICIOS GENERALES > LIMPIEZA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 2, 2, 'DIRECCIÓN DE GESTIÓN EDILICIA > SERVICIOS GENERALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 3, 3, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > DIRECCIÓN DE GESTIÓN EDILICIA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 4, 4, 'DIRECCIÓN NACIONAL DE EXPRESIONES FEDERALES > JEFATURA DE GABINETE DE EXPRESIONES FEDERALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 5, 5, 'SUBSECRETARÍA DE EXPRESIONES FEDERALES Y PARQUES TEMÁTICOS > DIRECCIÓN NACIONAL DE EXPRESIONES FEDERALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 6, 6, 'SECRETARÍA DE CONTENIDOS PÚBLICOS > SUBSECRETARÍA DE EXPRESIONES FEDERALES Y PARQUES TEMÁTICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 7, 7, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > SECRETARÍA DE CONTENIDOS PÚBLICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 8, 8, 'SERVICIOS GENERALES > CONTROL DE ACCESOS A');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 9, 9, 'SERVICIOS GENERALES > CONTROL DE ACCESOS B');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 10, 10, 'SERVICIOS GENERALES > OTROS SERVICIOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 11, 11, 'DIRECCIÓN DE GESTIÓN EDILICIA > MANTENIMIENTO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 12, 12, 'DIRECCIÓN DE GESTIÓN EDILICIA > SEGURIDAD');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 13, 13, 'DIRECCIÓN DE GESTIÓN EDILICIA > HIGIENE Y SEGURIDAD LABORAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 14, 14, 'DIRECCIÓN DE GESTIÓN EDILICIA > ESPACIOS FÍSICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 15, 15, 'DIRECCIÓN DE GESTIÓN EDILICIA > PLANIFICACIÓN Y CONTROL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 16, 16, 'DIRECCIÓN DE GESTIÓN EDILICIA > MESA DE AYUDA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 17, 17, 'DIRECCIÓN DE GESTIÓN EDILICIA > OPERATIVA Y LOGISTICA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 18, 18, 'DIRECCIÓN DE GESTIÓN EDILICIA > ADMINISTRACIÓN EDILICIA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 19, 19, 'DIRECCIÓN NACIONAL DE EXPRESIONES FEDERALES > DIRECCIÓN ADJUNTA DE EXPRESIONES FEDERALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 20, 20, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > PROGRAMACIÓN ARTISTICA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 21, 21, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > ADMINISTRACIÓN DE EXPRESIONES FEDERALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 22, 22, 'ADMINISTRACIÓN DE EXPRESIONES FEDERALES > BOLETERÍA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 23, 23, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > PRODUCCIÓN TÉCNICA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 24, 24, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > PRODUCCIÓN ARTISTICA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 25, 25, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > RELACIONES INSTITUCIONALES Y PROTOCOLO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 26, 26, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > PRENSA Y COMUNICACIÓN');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 27, 27, 'JEFATURA DE GABINETE DE EXPRESIONES FEDERALES > CONTENIDOS AUDIOVISUALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 28, 28, 'RELACIONES INSTITUCIONALES Y PROTOCOLO > SALAS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 29, 29, 'RELACIONES INSTITUCIONALES Y PROTOCOLO > VISITAS GUIADAS Y ATENCIÓN AL PÚBLICO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 30, 30, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > SECRETARÍA DE MEDIOS PÚBLICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 31, 31, 'SUBSECRETARÍA DE EXPRESIONES FEDERALES Y PARQUES TEMÁTICOS > DIRECCIÓN NACIONAL DE PARQUES TEMÁTICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 32, 32, 'SECRETARÍA DE CONTENIDOS PÚBLICOS > DIRECCIÓN NACIONAL DE CONTENIDOS PÚBLICOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 33, 33, 'DIRECCIÓN NACIONAL DE CONTENIDOS PÚBLICOS > CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 34, 34, 'CIARA > PRODUCCIÓN CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 35, 35, 'CIARA > SEÑALES CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 36, 36, 'SEÑALES CIARA > AQUA MAYOR');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 37, 37, 'SEÑALES CIARA > AQUA FEDERAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 38, 38, 'SEÑALES CIARA > PLATAFORMA CDA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 39, 39, 'CIARA > BACUA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 40, 40, 'BACUA > TECNICA BACUA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 41, 41, 'BACUA > DISTRIBUCIÓN BACUA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 42, 42, 'CIARA > PANORAMA FEDERAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 43, 43, 'CIARA > SEGUIMIENTO PRODUCCIÓN CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 44, 44, 'CIARA > ADMINISTRACIÓN CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 45, 45, 'CIARA > RECURSOS HUMANOS CIARA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 46, 46, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > PROTOCOLO Y CEREMONIAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 47, 47, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > PRENSA Y COMUNICACIÓN');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 48, 48, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > PRIVADA SIFEMECO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 49, 49, 'PRODUCCIÓN TÉCNICA > ILUMINACIÓN');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 50, 50, 'PRODUCCIÓN TÉCNICA > SONIDO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 51, 51, 'PRODUCCIÓN TÉCNICA > VIDEO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 52, 52, 'CONTENIDOS AUDIOVISUALES > POST PRODUCCIÓN');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 53, 53, 'CONTENIDOS AUDIOVISUALES > CLIPPING Y TRADUCCIÓN');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 54, 54, 'PRODUCCIÓN ARTISTICA > ARTES VISUALES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 55, 55, 'SISTEMA FEDERAL DE MEDIOS Y CONTENIDOS PÚBLICOS > DIRECCIÓN GENERAL TÉCNICA, ADMINISTRATIVA Y LEGAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 56, 56, 'DIRECCIÓN GENERAL TÉCNICA, ADMINISTRATIVA Y LEGAL > SUBDIRECCIÓN GENERAL TÉCNICA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 57, 57, 'DIRECCIÓN GENERAL TÉCNICA, ADMINISTRATIVA Y LEGAL > SUBDIRECCIÓN GENERAL ADMINISTRATIVA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 58, 58, 'DIRECCIÓN GENERAL TÉCNICA, ADMINISTRATIVA Y LEGAL > SUBDIRECCIÓN LEGAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 59, 59, 'SUBDIRECCIÓN GENERAL ADMINISTRATIVA > COMPRAS Y CONTRATACIONES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 60, 60, 'SUBDIRECCIÓN GENERAL ADMINISTRATIVA > PRESUPUESTO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 61, 61, 'SUBDIRECCIÓN GENERAL ADMINISTRATIVA > MESA DE ENTRADAS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 62, 62, 'SUBDIRECCIÓN GENERAL ADMINISTRATIVA > INFORMÁTICA Y TELECOMUNICACIONES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 63, 63, 'SUBDIRECCIÓN GENERAL TÉCNICA > COORDINACIÓN TÉCNICA OPERATIVA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 64, 64, 'SECRETARÍA DE MEDIOS PÚBLICOS > RADIO Y TELEVISIÓN ARGENTINA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 65, 65, 'SECRETARÍA DE MEDIOS PÚBLICOS > AGENCIA TELAM');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 66, 66, 'AUTOMOTORES > CHOFERES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 67, 67, 'PRIVADA SIFEMECO > AUTOMOTORES');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 68, 68, 'RECURSOS HUMANOS > SERVICIO MÉDICO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 69, 69, 'SUBDIRECCIÓN GENERAL ADMINISTRATIVA > RECURSOS HUMANOS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 70, 70, 'SEGURIDAD > BOMBEROS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 71, 71, 'SEGURIDAD > POLICÍA FEDERAL');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 72, 72, 'SEGURIDAD > EMPRESA SEGURIDAD PRIVADA MURATA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 73, 73, 'LIMPIEZA > EMPRESA DE LIMPIEZA IMPECABLE');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 74, 74, 'MANTENIMIENTO > EMPRESA ELEVACIÓN VERTICAL OTIS');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 75, 75, 'MANTENIMIENTO > EMPRESA MANTENIMIENTO EDILICIO ZOLMACO');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 76, 76, 'DIRECCIÓN NACIONAL DE ARQUITECTURA > INSPECCIÓN DE OBRA');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (13, TRUE, 77, 77, 'INSPECCIÓN DE OBRA > EMPRESA CONSTRUCTORA UTE ESUCO RIVA');

-- Insert de Personal
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 1 , 1 , 'DIRECCIÓN DE GESTIÓN EDILICIA > Martínez López, Alberto');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 2 , 2 , 'DIRECCIÓN DE GESTIÓN EDILICIA > Umpierrez, Manuel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 3 , 3 , 'DIRECCIÓN DE GESTIÓN EDILICIA > Caram, Adrian');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 4 , 4 , 'PLANIFICACIÓN Y CONTROL > Javier Rizzo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 5 , 5 , 'PLANIFICACIÓN Y CONTROL > Marcelo Restuccio');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 6 , 6 , 'PLANIFICACIÓN Y CONTROL > María Fernanda Sanz');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 7 , 7 , 'PLANIFICACIÓN Y CONTROL > Pablo Maccari');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 8 , 8 , 'OPERATIVA Y LOGISTICA > Soto, Jonatan');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 9 , 9 , 'OPERATIVA Y LOGISTICA > Marcote, Mariano');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 10 , 10 , 'OPERATIVA Y LOGISTICA > Meana, Adrian');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 11 , 11 , 'OPERATIVA Y LOGISTICA > Baez, Esteban');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 12 , 12 , 'OPERATIVA Y LOGISTICA > González, Nelson');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 13 , 13 , 'OPERATIVA Y LOGISTICA > Lotz, Guillermo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 14 , 14 , 'OPERATIVA Y LOGISTICA > Acosta, Hugo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 15 , 15 , 'OPERATIVA Y LOGISTICA > Chemes, Mariano');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 16 , 16 , 'OPERATIVA Y LOGISTICA > Goñi, Hernan');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 17 , 17 , 'OPERATIVA Y LOGISTICA > Vedoya, Emmanuel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 18 , 18 , 'OPERATIVA Y LOGISTICA > Treser, Carlos');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 19 , 19 , 'MESA DE AYUDA > Leyes, Sabrina');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 20 , 20 , 'MESA DE AYUDA > Lucano, Sandra');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 21 , 21 , 'MESA DE AYUDA > Herrera, Maria del Mar');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 22 , 22 , 'MESA DE AYUDA > Alberti, Cynthia');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 23 , 23 , 'MESA DE AYUDA > Valladares, Candela');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 24 , 24 , 'MESA DE AYUDA > Savignon, Leila');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 25 , 25 , 'ADMINISTRACIÓN EDILICIA > Daniel, Danira');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 26 , 26 , 'ADMINISTRACIÓN EDILICIA > Milanese, Fernando');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 27 , 27 , 'ADMINISTRACIÓN EDILICIA > Peinado, Magali');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 28 , 28 , 'CONTROL DE ACCESOS A > Fuentes Lanesan, Ruben');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 29 , 29 , 'CONTROL DE ACCESOS A > Carruthers, Federico');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 30 , 30 , 'CONTROL DE ACCESOS A > Velazquez, Eduardo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 31 , 31 , 'CONTROL DE ACCESOS A > Herrera, Lara Mariela');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 32 , 32 , 'CONTROL DE ACCESOS A > Granero, Maria Noel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 33 , 33 , 'CONTROL DE ACCESOS A > Gomez Garnero, Ignacio');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 34 , 34 , 'CONTROL DE ACCESOS B > Gaitan, Matias');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 35 , 35 , 'CONTROL DE ACCESOS B > Pacheco, Franco');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 36 , 36 , 'CONTROL DE ACCESOS B > Castiello, Nicolas');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 37 , 37 , 'CONTROL DE ACCESOS B > Fuentes Lanesan, Manuel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 38 , 38 , 'CONTROL DE ACCESOS B > Biondo, Paula Lucia');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 39 , 39 , 'LIMPIEZA > Zeniuk, Gabriel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 40 , 40 , 'LIMPIEZA > Dominguez, Emiliano');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 41 , 41 , 'LIMPIEZA > Weidert, Fernando');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 42 , 42 , 'LIMPIEZA > Vargas, Nancy');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 43 , 43 , 'LIMPIEZA > Dialissandro, Jorge');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 44 , 44 , 'LIMPIEZA > Leal, Camila');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 45 , 45 , 'LIMPIEZA > Cabrera, Valeria');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 46 , 46 , 'MANTENIMIENTO > Sanchez, Gabriel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 47 , 47 , 'MANTENIMIENTO > Franceschi, Santiago');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 48 , 48 , 'MANTENIMIENTO > Balcazar, Jorge');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 49 , 49 , 'MANTENIMIENTO > Castillo, Enzo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 50 , 50 , 'MANTENIMIENTO > Gómez, Wilson');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 51 , 51 , 'MANTENIMIENTO > Hurtado, Ricardo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 52 , 52 , 'SEGURIDAD > Carca, Gustavo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 53 , 53 , 'SEGURIDAD > Riccitelli, Miguel Angel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 54 , 54 , 'SEGURIDAD > Rojas, Mirta');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 55 , 55 , 'SEGURIDAD > Ochoa, Fabian');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 56 , 56 , 'SEGURIDAD > Speake, Randy');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 57 , 57 , 'HIGIENE Y SEGURIDAD > Lirusso, Raul');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 58 , 58 , 'HIGIENE Y SEGURIDAD > Chara Scardigio, Juan Manuel');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 59 , 59 , 'HIGIENE Y SEGURIDAD > Pellegrotti, Antonella');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 60 , 60 , 'HIGIENE Y SEGURIDAD > Ciccotosto, Romina');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 61 , 61 , 'ESPACIOS FÍSICOS > Maximiliano Seif');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 62 , 62 , 'ESPACIOS FÍSICOS > Mizzau, Carolina');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 63 , 63 , 'ESPACIOS FÍSICOS > Macia, Pablo');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 64 , 64 , 'ESPACIOS FÍSICOS > Toledo Widensky, Julieta');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 65 , 65 , 'ESPACIOS FÍSICOS > Piccolomini, Sebastian');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 66 , 66 , 'ESPACIOS FÍSICOS > Andino, Florencia');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 67 , 67 , 'ESPACIOS FÍSICOS > Fabre, Germán');
INSERT INTO custom_field_enumerations(custom_field_id,active,id_ori,position,name) VALUES (14, TRUE, 68 , 68 , 'ESPACIOS FÍSICOS > Cagnola, Leticia');